---
apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: kanban-stats-collector
spec:
  schedule: 0 1,17 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kanban-stats-collector
            image: mariusgrigoriu/kanban-stats
            command:
            - /kanban-stats
            args:
            - -boardid
            - 534efa63a3a33edc034ac3d1
            - -v
            - -influxurl
            - http://kanban-stats.default.svc.cluster.local:8086
            env:
              - name: TRELLO_KEY
                valueFrom:
                  secretKeyRef:
                    name: kanban-stats
                    key: TRELLO_KEY
              - name: TRELLO_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: kanban-stats
                    key: TRELLO_TOKEN
          restartPolicy: OnFailure
