---
  apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "kanban-stats"
    namespace: "default"
    labels:
      app: "kanban-stats"
  spec:
    selector:
      app: "kanban-stats"
    ports:
      - name: "influxdb"
        port: 8086
        protocol: "TCP"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kanban-stats
  namespace: default
  labels:
    app: kanban-stats
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kanban-stats
    spec:
      containers:
      - name: influxdb
        args:
        - -config
        - /influxdb/config
        command:
        - influxd
        image: mariusgrigoriu/influxdb
        imagePullPolicy: Always
        ports:
        - name: influxdb
          containerPort: 8086
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8083
            scheme: HTTP
        volumeMounts:
        - mountPath: /influxdb
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: kanban-stats-influxdb-claim
